name: sports_league_app
description: A new Flutter project.
publish_to: 'none' # 移除這行可發佈到 pub.dev
version: 1.4.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase 套件（與 Flutter 3.19 相容）
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  google_sign_in: ^6.3.0

  # 其他常用套件
  cupertino_icons: ^1.0.2
  uuid: ^4.2.1
  intl: ^0.20.2
  js: ^0.7.2 # 如果你是 Flutter Web 使用者需要操作 JS，保留它

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
