// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeS2gKY2G-ieC-pNGnJIk4_e3H9QYlDaE',
    appId: '1:757686243952:web:fe291194a5e7b463a3dab5',
    messagingSenderId: '757686243952',
    projectId: 'sports-league-app-d25e2',
    authDomain: 'sports-league-app-d25e2.firebaseapp.com',
    databaseURL: 'https://sports-league-app-d25e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sports-league-app-d25e2.firebasestorage.app',
    measurementId: 'G-LX4JNFNDJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlphPjw9Ivsl6Uo9h33Y10T-2LwoIRxpQ',
    appId: '1:757686243952:android:bc72f4d367ad7f1ca3dab5',
    messagingSenderId: '757686243952',
    projectId: 'sports-league-app-d25e2',
    databaseURL: 'https://sports-league-app-d25e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sports-league-app-d25e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrvBKZLZ_JTgnnULvXRIFJhsxBQVea2k',
    appId: '1:757686243952:ios:d2b738c7e4ed241da3dab5',
    messagingSenderId: '757686243952',
    projectId: 'sports-league-app-d25e2',
    databaseURL: 'https://sports-league-app-d25e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sports-league-app-d25e2.firebasestorage.app',
    iosBundleId: 'com.example.sportsLeagueApp',
  );
}
